
CREATE TABLE IF NOT EXISTS AIRLINE (
    AIRLINE_ID          INTEGER NOT NULL,
    AIRLINE_NAME        CHAR,
    ALIAS               CHAR,
    IATA                CHAR,
    ICAO                CHAR,
    CALLSIGN            CHAR,
    COUNTRY             CHAR,
    ACTIVE              CHAR(1),
    PRIMARY KEY (AIRLINE_ID)
);

CREATE TABLE IF NOT EXISTS TICKET (
    TICKET_ID           INTEGER NOT NULL,
    PASSENGER_ID        INTEGER,
    CLASS               CHAR,
    GATE                VARCHAR(2),
    PRIMARY KEY (TICKET_ID)
);

CREATE TABLE IF NOT EXISTS PASSANGER (
    PASSENGER_ID        INTEGER NOT NULL,
    FIRST_NAME          CHAR(20),
    LAST_NAME           CHAR(20),
    FREQUENT_FLYER_NUMBER   INTEGER,
    TSA_PRECHECK        CHAR(1),
    EMAIL_ADDRESS       VARCHAR(20),
    PHONE_NUMBER        VARCHAR(15),
    PRIMARY KEY (PASSENGER_ID)
);

CREATE TABLE IF NOT EXISTS AIRPORT (
    AIRPORT_ID          INTEGER NOT NULL,
    AIRPORT_NAME        CHAR(20),
    AIRPORT_ADDRESS     VARCHAR(20),
    PHONE_NUMBER        VARCHAR(15),
    AIRLINE_ID          INTEGER,
    PRIMARY KEY (AIRPORT_ID)
);

CREATE TABLE IF NOT EXISTS TERMINAL (
    TERMINAL_ID         INTEGER NOT NULL,
    NUMBER_OF_GATES     INTEGER,
    PRIMARY KEY (TERMINAL_ID)
);

CREATE TABLE IF NOT EXISTS GATE (
    GATE_ID             INTEGER NOT NULL,
    AIRLINE_ID          INTEGER,
    PRIMARY KEY (GATE_ID)
);

CREATE TABLE IF NOT EXISTS FLIGHT (
    FLIGHT_ID           INTEGER NOT NULL,
    PLANE_ID            INTEGER,
    DEPARTURE_TIME      TIME,
    DESTINATION         VARCHAR(20),
    BOARDING_TIME       TIME,
    SOURCE              CHAR,
    DURATION            TIME,
    PRIMARY KEY (FLIGHT_ID)
);


CREATE TABLE IF NOT EXISTS FLIGHT_ATTENDANT (
    FLIGHT_ATTENDANT_ID INTEGER NOT NULL,
    HIRE_DATE           DATE,
    FIRST_NAME          CHAR(20),
    LAST_NAME           CHAR(20),
    PRIMARY KEY (FLIGHT_ATTENDANT_ID)
);

CREATE TABLE IF NOT EXISTS PILOT (
    PILOT_ID            INTEGER NOT NULL,
    HIRE_DATE           DATE,
    FIRST_NAME          CHAR(20),
    LAST_NAME           CHAR(20),
    PRIMARY KEY (PILOT_ID)
);

CREATE TABLE IF NOT EXISTS PLANE (
    PLANE_ID            INTEGER NOT NULL,
    PLANE_NAME          VARCHAR(80),
    IATA_CODE           VARCHAR(3),
    ICAO_CODE           VARCHAR(4),
    PRIMARY KEY (PLANE_ID)
);
