
CREATE TABLE IF NOT EXISTS AIRLINE (
    AIRLINE_ID          INTEGER;
    NUMBER_OF_PLANES    INTEGER;
    AIRLINE_NAME        CHAR(20);
    PLANE_ID            INTEGER;
    PRIMARY KEY (AIRLINE_ID);
);

CREATE TABLE IF NOT EXISTS BOOKINGS (
    BOOKINGS_ID         INTEGER;
    TICKETS_AVAILABLE   INTEGER;
    TICKETS_SOLD        INTEGER;
    SEAT_SELECTION      VARCHAR(2);
    PRICE               INTEGER;
    PRIMARY KEY (BOOKINGS_ID);
);

CREATE TABLE IF NOT EXISTS PASSANGER (
    PASSENGER_ID        INTEGER;
    FIRST_NAME          CHAR(20);
    LAST_NAME           CHAR(20);
    PRIMARY KEY (PASSENGER_ID);
);

CREATE TABLE IF NOT EXISTS AIRPORT (
    AIRPORT_ID          INTEGER;
    AIRPORT_NAME        CHAR(20);
    AIRPORT_ADDRESS     VARCHAR;
    PHONE_NUMBER        VARCHAR(15);
    PRIMARY KEY (AIRPORT_ID);
);

CREATE TABLE IF NOT EXISTS TERMINAL (
    TERMINAL_ID         INTEGER;
    NUMBER_OF_GATES     INTEGER;
    PRIMARY KEY (TERMINAL_ID);
);

CREATE TABLE IF NOT EXISTS GATE (
    GATE_ID             INTEGER;
    AIRLINE_ID          INTEGER;
    PRIMARY KEY (GATE_ID);
);

CREATE TABLE IF NOT EXISTS FLIGHT (
    FLIGHT_ID           INTEGER;
    FLIGHT_CODE         INTEGER;
    DEPARTURE_TIME      TIME;
    DESTINATION         VARCHAR;
    AIRLINER_ID         INTEGER;
    BOARDING_TIME       TIME;
    DURATION            TIME;
    ARRIVAL_GATE        VARCHAR(2);
    PRIMARY KEY (FLIGHT_ID);
);

CREATE TABLE IF NOT EXISTS HELPDESK (
    HELP_DESK_ID        INTEGER;
    HIRE_DATE           DATE;
    FIRST_NAME          CHAR(20);
    LAST_NAME           CHAR(20);
    PRIMARY KEY (HELP_DESK_ID);
);

CREATE TABLE IF NOT EXISTS FLIGHT_ATTENDANT (
    FLIGHT_ATTENDANT_ID INTEGER;
    HIRE_DATE           DATE;
    FIRST_NAME          CHAR(20);
    LAST_NAME           CHAR(20);
    PRIMARY KEY (FLIGHT_ATTENDANT_ID);
);

CREATE TABLE IF NOT EXISTS PILOT (
    PILOT_ID            INTEGER;
    HIRE_DATE           DATE;
    FIRST_NAME          CHAR(20);
    LAST_NAME           CHAR(20);
    PRIMARY KEY (PILOT_ID);
);

CREATE TABLE IF NOT EXISTS PLANE (
    PLANE_ID            INTEGER;
    PLANE_TYPE          VARCHAR;
    NUMBER_OF_SEATS     INTEGER;
    LAST_INSPECTION     DATE;
);


















